---
abstract: 'Automatically set and update fields'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
build_requires:
  DBICx::TestDatabase: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-DynamicDefault
no_index:
  directory:
    - inc
    - t
provides:
  DBIx::Class::DynamicDefault:
    file: lib/DBIx/Class/DynamicDefault.pm
    version: 0.01
requires:
  DBIx::Class: 0
  parent: 0
version: 0.01
