---
abstract: 'Automatically set and update fields'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
build_requires:
  DBICx::TestDatabase: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-DynamicDefault
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
